# Generated by Django 4.2.7 on 2026-02-27 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_content_manager', models.BooleanField(default=False, verbose_name='Content Manager')),
                ('is_api_viewer', models.BooleanField(default=True, verbose_name='API Viewer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cms_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CMS User',
                'verbose_name_plural': 'CMS Users',
                'db_table': 'cms_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CMSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('cms_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_sessions', to='authentication.cmsuser', verbose_name='CMS User')),
            ],
            options={
                'verbose_name': 'CMS Session',
                'verbose_name_plural': 'CMS Sessions',
                'db_table': 'cms_sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['cms_user', 'is_active'], name='cms_session_cms_use_9699c9_idx'), models.Index(fields=['session_key'], name='cms_session_session_68afd5_idx'), models.Index(fields=['last_activity'], name='cms_session_last_ac_d27926_idx')],
            },
        ),
    ]
