# Generated by Django 4.2.7 on 2026-02-26 22:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('responded', 'Responded'), ('archived', 'Archived')], default='new', max_length=10, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('referral_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='How did you hear about us?')),
                ('newsletter_subscription', models.BooleanField(default=False, verbose_name='Subscribe to newsletter')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'db_table': 'contact_submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='contact_sub_status_a37629_idx'), models.Index(fields=['created_at'], name='contact_sub_created_54b02f_idx'), models.Index(fields=['email'], name='contact_sub_email_903821_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_message', models.TextField(verbose_name='Response Message')),
                ('response_email_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Responded At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('responded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_responses', to=settings.AUTH_USER_MODEL, verbose_name='Responded By')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='contacts.contactsubmission', verbose_name='Contact Submission')),
            ],
            options={
                'verbose_name': 'Contact Response',
                'verbose_name_plural': 'Contact Responses',
                'db_table': 'contact_responses',
                'ordering': ['-created_at'],
            },
        ),
    ]
